version: '3.8'

services:
  api:
    build: ./server
    container_name: gemini-api
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - gemini-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: gemini-redis
    volumes:
      - redis-data:/data
    networks:
      - gemini-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: gemini-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - api
    networks:
      - gemini-network
    restart: unless-stopped

networks:
  gemini-network:
    driver: bridge

volumes:
  redis-data: