version: '3.8'

services:
  api:
    build:
      context: ./server
    ports:
      - "8001:8000"
    volumes:
      - ./server/app:/app/app
    environment:
      - REDIS_URL=redis://redis:6379
      - GEMINI_API_KEY=AIzaSyDVkgRk8wG9dU5k9h4AIfFkitAkrYTfFz8
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: "redis:7-alpine"
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 5