version: '3.8'

services:
  gemini-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GEMINI_API_KEY=AIzaSyDVkgRk8wG9dU5k9h4AIfFkitAkrYTfFz8
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - PORT=8001
    volumes:
      - /tmp/gemini-repos:/tmp/gemini-repos
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - gemini-network

  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - gemini-network

  nginx-proxy:
    image: nginxproxy/nginx-proxy:latest
    container_name: server-ts-nginx-proxy-1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
    restart: unless-stopped
    networks:
      - gemini-network

  nginx-proxy-acme:
    image: nginxproxy/acme-companion:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - acme-data:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=admin@27cobalto.com
      - NGINX_PROXY_CONTAINER=server-ts-nginx-proxy-1
    depends_on:
      - nginx-proxy
    restart: unless-stopped
    networks:
      - gemini-network

  api-proxy:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - VIRTUAL_HOST=gemini.27cobalto.com
      - LETSENCRYPT_HOST=gemini.27cobalto.com
      - LETSENCRYPT_EMAIL=admin@27cobalto.com
    depends_on:
      - gemini-api
    restart: unless-stopped
    networks:
      - gemini-network

volumes:
  redis-data:
  nginx-certs:
  nginx-vhost:
  nginx-html:
  acme-data:

networks:
  gemini-network:
    driver: bridge