openapi: 3.0.0
info:
  title: Gemini Agent API
  version: 1.0.0
  description: API for orchestrating a Gemini-powered agent for GitHub automation.

paths:
  /v1/github/execute:
    post:
      summary: Execute a step in a GitHub agent conversation
      operationId: execute_github_step
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AgentRequest'
      responses:
        '200':
          description: Successfully returned the next action for the client to execute.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AgentResponse'
        '500':
          description: Internal server error.

components:
  schemas:
    AgentRequest:
      type: object
      properties:
        conversation_id:
          type: string
          description: "Unique ID for the conversation (e.g., 'issue-123'). If not provided, a new conversation is started."
          nullable: true
        prompt:
          type: object
          description: "The initial prompt context. Only required for the first request in a conversation."
          nullable: true
          properties:
            issue_title:
              type: string
            issue_body:
              type: string
            github_context:
              type: object
              description: "Additional context from the GitHub event."
        tool_response:
          type: object
          description: "The result of a tool execution requested by the agent in the previous step."
          nullable: true
          properties:
            tool_name:
              type: string
              description: "The name of the tool that was executed (e.g., 'run_shell_command')."
            command:
              type: string
            stdout:
              type: string
            stderr:
              type: string
            exit_code:
              type: integer

    AgentResponse:
      type: object
      properties:
        conversation_id:
          type: string
          description: "The unique ID for the ongoing conversation."
        action:
          type: string
          enum: [run_shell_command, read_file, write_file, finish]
          description: "The next action the client should perform."
        command:
          type: string
          description: "The shell command to execute. Only present if action is 'run_shell_command'."
          nullable: true
        file_path:
          type: string
          description: "The path to the file for read/write operations. Only present for file actions."
          nullable: true
        content:
          type: string
          description: "The content to write to a file. Only present for 'write_file' action."
          nullable: true
        message:
          type: string
          description: "A message to the user. Only present if action is 'finish'."
          nullable: true
